# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: apenas
# "service" is the name of this project. This will also be added to your AWS resource names.
service: foodiary-api

plugins:
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs22.x
  architecture: arm64
  environment:
    #GETting from .env
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}

package: 
  individually: true

build:
  esbuild:
   minify: true
   sourcemap: false

functions:
  sign-in:
    handler: src/functions/sign-in.handler
    events:
      - httpApi:
          method: POST
          path: /sign-in
  sign-up:
    handler: src/functions/sign-up.handler
    events:
      - httpApi:
          method: POST
          path: /sign-up
          
  me:
    handler: src/functions/me.handler
    events:
      - httpApi:
          method: GET
          path: /me
          

  create-meal:
    handler: src/functions/create-meal.handler
    events:
      - httpApi:
          method: POST
          path: /meals

  list-meals:
    handler: src/functions/list-meals.handler
    events:
      - httpApi:
          method: GET
          path: /meals
